name: Pay E2E

on:
  pull_request:
    types: [opened, edited, synchronize]
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  pay-e2e:
    name: Pay E2E
    runs-on: ubuntu-latest
    concurrency:
      group: yttrium-pay-e2e-${{ github.head_ref || github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.4
      - run: rustup update stable && rustup default stable
      - run: cargo test -p yttrium --features=test_pay_api pay::e2e_tests -- --nocapture
        env:
          REOWN_PROJECT_ID: ${{ vars.REOWN_PROJECT_ID }}
          WALLET_PROJECT_ID: ${{ secrets.WALLET_PROJECT_ID }}
          TEST_WALLET_PRIVATE_KEY: ${{ secrets.TEST_WALLET_PRIVATE_KEY }}
          MERCHANT_API_KEY: ${{ secrets.MERCHANT_API_KEY }}
          MERCHANT_ID: merchant-1768556907
          RUST_BACKTRACE: 1
          RUST_LOG: yttrium=trace
